/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    catalogs: Catalog;
    'data-exports': DataExport;
    datasets: Dataset;
    'dataset-schemas': DatasetSchema;
    'deletion-audit-log': DeletionAuditLog;
    'import-files': ImportFile;
    'import-jobs': ImportJob;
    'scheduled-imports': ScheduledImport;
    events: Event;
    users: User;
    'user-usage': UserUsage;
    media: Media;
    'location-cache': LocationCache;
    'geocoding-providers': GeocodingProvider;
    pages: Page;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    catalogs: CatalogsSelect<false> | CatalogsSelect<true>;
    'data-exports': DataExportsSelect<false> | DataExportsSelect<true>;
    datasets: DatasetsSelect<false> | DatasetsSelect<true>;
    'dataset-schemas': DatasetSchemasSelect<false> | DatasetSchemasSelect<true>;
    'deletion-audit-log': DeletionAuditLogSelect<false> | DeletionAuditLogSelect<true>;
    'import-files': ImportFilesSelect<false> | ImportFilesSelect<true>;
    'import-jobs': ImportJobsSelect<false> | ImportJobsSelect<true>;
    'scheduled-imports': ScheduledImportsSelect<false> | ScheduledImportsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'user-usage': UserUsageSelect<false> | UserUsageSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'location-cache': LocationCacheSelect<false> | LocationCacheSelect<true>;
    'geocoding-providers': GeocodingProvidersSelect<false> | GeocodingProvidersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'main-menu': MainMenu;
    footer: Footer;
    branding: Branding;
    settings: Setting;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'main-menu': MainMenuSelect<false> | MainMenuSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    branding: BrandingSelect<false> | BrandingSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      'dataset-detection': TaskDatasetDetection;
      'detect-schema': TaskDetectSchema;
      'analyze-duplicates': TaskAnalyzeDuplicates;
      'validate-schema': TaskValidateSchema;
      'create-schema-version': TaskCreateSchemaVersion;
      'geocode-batch': TaskGeocodeBatch;
      'create-events': TaskCreateEvents;
      'cleanup-approval-locks': TaskCleanupApprovalLocks;
      'url-fetch': TaskUrlFetch;
      'schedule-manager': TaskScheduleManager;
      'cleanup-stuck-scheduled-imports': TaskCleanupStuckScheduledImports;
      'process-pending-retries': TaskProcessPendingRetries;
      'quota-reset': TaskQuotaReset;
      'cache-cleanup': TaskCacheCleanup;
      'schema-maintenance': TaskSchemaMaintenance;
      'data-export': TaskDataExport;
      'data-export-cleanup': TaskDataExportCleanup;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalogs".
 */
export interface Catalog {
  id: number;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * URL-friendly identifier (auto-generated from name if not provided)
   */
  slug?: string | null;
  /**
   * User who created this catalog
   */
  createdBy?: (number | null) | User;
  isPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  role?: ('user' | 'admin' | 'editor') | null;
  isActive?: boolean | null;
  lastLoginAt?: string | null;
  /**
   * How this user account was created
   */
  registrationSource?: ('admin' | 'self') | null;
  /**
   * User trust level determines resource quotas and rate limits
   */
  trustLevel: '0' | '1' | '2' | '3' | '4' | '5';
  /**
   * Resource quotas for this user (automatically set based on trust level)
   */
  quotas?: {
    /**
     * Maximum number of active scheduled imports (-1 for unlimited)
     */
    maxActiveSchedules?: number | null;
    /**
     * Maximum URL fetches per day (-1 for unlimited)
     */
    maxUrlFetchesPerDay?: number | null;
    /**
     * Maximum file uploads per day (-1 for unlimited)
     */
    maxFileUploadsPerDay?: number | null;
    /**
     * Maximum events per single import (-1 for unlimited)
     */
    maxEventsPerImport?: number | null;
    /**
     * Maximum total events allowed (-1 for unlimited)
     */
    maxTotalEvents?: number | null;
    /**
     * Maximum import jobs per day (-1 for unlimited)
     */
    maxImportJobsPerDay?: number | null;
    /**
     * Maximum file size in MB for uploads
     */
    maxFileSizeMB?: number | null;
    /**
     * Maximum number of catalogs per user (-1 for unlimited)
     */
    maxCatalogsPerUser?: number | null;
  };
  /**
   * Custom quota overrides (JSON format) - overrides trust level defaults
   */
  customQuotas?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Account deletion status
   */
  deletionStatus?: ('active' | 'pending_deletion' | 'deleted') | null;
  /**
   * When the user requested account deletion
   */
  deletionRequestedAt?: string | null;
  /**
   * When the account will be permanently deleted
   */
  deletionScheduledAt?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * User data export requests and their status
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-exports".
 */
export interface DataExport {
  id: number;
  /**
   * User who requested the export
   */
  user: number | User;
  /**
   * Current status of the export request
   */
  status: 'pending' | 'processing' | 'ready' | 'failed' | 'expired';
  /**
   * When the export was requested
   */
  requestedAt: string;
  /**
   * When the export finished processing
   */
  completedAt?: string | null;
  /**
   * When the download link expires (7 days after completion)
   */
  expiresAt?: string | null;
  /**
   * Internal file path for the export ZIP (for cleanup)
   */
  filePath?: string | null;
  /**
   * File size in bytes
   */
  fileSize?: number | null;
  /**
   * Number of times the export has been downloaded
   */
  downloadCount?: number | null;
  /**
   * Export summary with record counts
   */
  summary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Error details if export failed
   */
  errorLog?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datasets".
 */
export interface Dataset {
  id: number;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * URL-friendly identifier (auto-generated from name if not provided)
   */
  slug?: string | null;
  catalog: number | Catalog;
  /**
   * Denormalized from catalog.createdBy for zero-query owner access control
   */
  catalogCreatorId?: number | null;
  /**
   * Denormalized from catalog.isPublic for zero-query access control
   */
  catalogIsPublic?: boolean | null;
  /**
   * ISO-639-3 code: 3 lowercase letters (e.g., eng, deu, fra)
   */
  language: string;
  isPublic?: boolean | null;
  /**
   * User who created this dataset
   */
  createdBy?: (number | null) | User;
  /**
   * Additional metadata for the entity
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  idStrategy?: {
    /**
     * How to generate unique IDs for events
     */
    type: 'external' | 'computed' | 'auto' | 'hybrid';
    /**
     * JSON path to ID field (e.g., 'id' or 'metadata.uuid')
     */
    externalIdPath?: string | null;
    /**
     * Fields to combine for unique hash
     */
    computedIdFields?:
      | {
          /**
           * Path to field to include in hash
           */
          fieldPath: string;
          id?: string | null;
        }[]
      | null;
    /**
     * What to do when duplicate is found
     */
    duplicateStrategy?: ('skip' | 'update' | 'version') | null;
  };
  schemaConfig?: {
    /**
     * Enable schema detection and validation
     */
    enabled?: boolean | null;
    /**
     * Require manual approval for ALL schema changes
     */
    locked?: boolean | null;
    /**
     * Allow automatic schema growth (new optional fields, new enum values)
     */
    autoGrow?: boolean | null;
    /**
     * Automatically approve non-breaking schema changes
     */
    autoApproveNonBreaking?: boolean | null;
    /**
     * Block entire import if any events fail validation
     */
    strictValidation?: boolean | null;
    /**
     * Allow automatic type transformations during import
     */
    allowTransformations?: boolean | null;
    /**
     * Maximum nesting depth for schema detection
     */
    maxSchemaDepth?: number | null;
    /**
     * Threshold for enum detection
     */
    enumThreshold?: number | null;
    /**
     * How to detect enum fields
     */
    enumMode?: ('count' | 'percentage') | null;
  };
  deduplicationConfig?: {
    /**
     * Enable duplicate detection during imports
     */
    enabled?: boolean | null;
    /**
     * What to do when duplicate is found
     */
    strategy?: ('skip' | 'update' | 'version') | null;
  };
  /**
   * Statistics and metadata about each field
   */
  fieldMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Rules for handling type mismatches
   */
  typeTransformations?:
    | {
        /**
         * JSON path to field (e.g., 'temperature' or 'location.altitude')
         */
        fieldPath: string;
        fromType: 'string' | 'number' | 'boolean' | 'null' | 'array' | 'object';
        toType: 'string' | 'number' | 'boolean' | 'date' | 'array' | 'object';
        transformStrategy: 'parse' | 'cast' | 'custom' | 'reject';
        /**
         * Function(value, context) => transformedValue
         */
        customTransform?: string | null;
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Transform rules applied to incoming data before validation (e.g., field renames)
   */
  importTransforms?:
    | {
        /**
         * Unique identifier for this transform rule
         */
        id: string;
        /**
         * Type of transformation to apply
         */
        type: 'rename';
        /**
         * Source field path in import file (e.g., 'date' or 'user.email')
         */
        from: string;
        /**
         * Target field path in dataset schema (e.g., 'start_date' or 'contact.email')
         */
        to: string;
        /**
         * Uncheck to disable without deleting
         */
        active?: boolean | null;
        /**
         * When this transform was created
         */
        addedAt?: string | null;
        /**
         * User who created this transform
         */
        addedBy?: (number | null) | User;
        /**
         * Confidence score if auto-detected (0-100)
         */
        confidence?: number | null;
        /**
         * Whether this transform was suggested by auto-detection
         */
        autoDetected?: boolean | null;
      }[]
    | null;
  enumDetection?: {
    mode?: ('count' | 'percentage' | 'disabled') | null;
    /**
     * Max unique values (count mode) or min percentage (percentage mode)
     */
    threshold?: number | null;
  };
  geoFieldDetection?: {
    /**
     * Automatically detect latitude/longitude fields
     */
    autoDetect?: boolean | null;
    /**
     * Override: JSON path to latitude (detected: location.lat, lat, latitude)
     */
    latitudePath?: string | null;
    /**
     * Override: JSON path to longitude (detected: location.lng, lng, lon, longitude)
     */
    longitudePath?: string | null;
  };
  /**
   * Override language-aware auto-detection of field mappings. Leave empty to use automatic detection based on dataset language.
   */
  fieldMappingOverrides?: {
    /**
     * Override detected title field (e.g., 'event_name', 'titel', 'titre')
     */
    titlePath?: string | null;
    /**
     * Override detected description field (e.g., 'details', 'beschreibung', 'détails')
     */
    descriptionPath?: string | null;
    /**
     * Override detected location name field (e.g., 'venue', 'place', 'ort', 'lieu')
     */
    locationNamePath?: string | null;
    /**
     * Override detected timestamp field (e.g., 'created_at', 'datum', 'date')
     */
    timestampPath?: string | null;
    /**
     * Override detected latitude field (e.g., 'lat', 'latitude', 'y_coord')
     */
    latitudePath?: string | null;
    /**
     * Override detected longitude field (e.g., 'lon', 'longitude', 'x_coord')
     */
    longitudePath?: string | null;
    /**
     * Override detected location field (e.g., 'address', 'location', 'venue', 'city')
     */
    locationPath?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Schema versions for datasets with full change tracking
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dataset-schemas".
 */
export interface DatasetSchema {
  id: number;
  /**
   * Dataset this schema belongs to
   */
  dataset: number | Dataset;
  /**
   * Schema version number (auto-incremented)
   */
  versionNumber: number;
  displayName?: string | null;
  /**
   * JSON Schema Draft 7
   */
  schema:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Field statistics and metadata
   */
  fieldMetadata:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Number of events in the dataset when this schema was generated
   */
  eventCountAtCreation?: number | null;
  schemaSummary?: {
    totalFields?: number | null;
    newFields?:
      | {
          path?: string | null;
          id?: string | null;
        }[]
      | null;
    removedFields?:
      | {
          path?: string | null;
          id?: string | null;
        }[]
      | null;
    typeChanges?:
      | {
          path?: string | null;
          oldType?: string | null;
          newType?: string | null;
          id?: string | null;
        }[]
      | null;
    enumChanges?:
      | {
          path?: string | null;
          addedValues?:
            | {
                [k: string]: unknown;
              }
            | unknown[]
            | string
            | number
            | boolean
            | null;
          removedValues?:
            | {
                [k: string]: unknown;
              }
            | unknown[]
            | string
            | number
            | boolean
            | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Import jobs that contributed to this schema
   */
  importSources?:
    | {
        import: number | ImportJob;
        recordCount?: number | null;
        batchCount?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Whether this schema requires manual approval
   */
  approvalRequired?: boolean | null;
  approvedBy?: (number | null) | User;
  approvalNotes?: string | null;
  /**
   * Was automatically approved due to safe changes
   */
  autoApproved?: boolean | null;
  /**
   * Conflicts that require manual resolution
   */
  conflicts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Detected or configured field mappings for standard event properties
   */
  fieldMappings?: {
    /**
     * Path to title/name field in source data
     */
    titlePath?: string | null;
    /**
     * Path to description/details field in source data
     */
    descriptionPath?: string | null;
    /**
     * Path to location/venue name field in source data
     */
    locationNamePath?: string | null;
    /**
     * Path to timestamp/date field in source data
     */
    timestampPath?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Unified import processing pipeline
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-jobs".
 */
export interface ImportJob {
  id: number;
  /**
   * Source file for this import job
   */
  importFile: number | ImportFile;
  /**
   * Target dataset for imported data
   */
  dataset: number | Dataset;
  /**
   * Sheet index for Excel files (0-based)
   */
  sheetIndex?: number | null;
  /**
   * Current processing stage
   */
  stage:
    | 'analyze-duplicates'
    | 'detect-schema'
    | 'validate-schema'
    | 'await-approval'
    | 'create-schema-version'
    | 'geocode-batch'
    | 'create-events'
    | 'completed'
    | 'failed';
  progress?: {
    /**
     * Detailed progress information for each processing stage
     */
    stages?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Overall progress percentage (0-100), weighted by stage time estimates
     */
    overallPercentage?: number | null;
    /**
     * Estimated completion time for the entire import
     */
    estimatedCompletionTime?: string | null;
  };
  /**
   * Detected JSON Schema from data
   */
  schema?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Progressive schema builder state for continuity across batches
   */
  schemaBuilderState?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Detected or configured field mappings for standard event properties
   */
  detectedFieldMappings?: {
    /**
     * Path to title/name field in source data
     */
    titlePath?: string | null;
    /**
     * Path to description/details field in source data
     */
    descriptionPath?: string | null;
    /**
     * Path to location/venue name field in source data (for display)
     */
    locationNamePath?: string | null;
    /**
     * Path to timestamp/date field in source data
     */
    timestampPath?: string | null;
    /**
     * Path to latitude coordinate field in source data
     */
    latitudePath?: string | null;
    /**
     * Path to longitude coordinate field in source data
     */
    longitudePath?: string | null;
    /**
     * Path to location/address field in source data (for geocoding)
     */
    locationPath?: string | null;
  };
  schemaValidation?: {
    /**
     * Whether schema is compatible with dataset schema
     */
    isCompatible?: boolean | null;
    /**
     * List of breaking schema changes
     */
    breakingChanges?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * New fields detected (auto-grow candidates)
     */
    newFields?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Auto-detected field rename suggestions with confidence scores
     */
    transformSuggestions?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Whether manual approval is required
     */
    requiresApproval?: boolean | null;
    /**
     * Reason why approval is required
     */
    approvalReason?: string | null;
    /**
     * Whether schema changes were approved
     */
    approved?: boolean | null;
    /**
     * User who approved the schema
     */
    approvedBy?: (number | null) | User;
    /**
     * When schema was approved
     */
    approvedAt?: string | null;
  };
  /**
   * The schema version this import was validated against
   */
  datasetSchemaVersion?: (number | null) | DatasetSchema;
  duplicates?: {
    /**
     * Deduplication strategy used (external-id, computed-hash, etc.)
     */
    strategy?: string | null;
    /**
     * Duplicates found within this import
     */
    internal?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Duplicates found with existing events
     */
    external?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    summary?: {
      /**
       * Total rows analyzed
       */
      totalRows?: number | null;
      /**
       * Unique rows after deduplication
       */
      uniqueRows?: number | null;
      /**
       * Duplicates within import
       */
      internalDuplicates?: number | null;
      /**
       * Duplicates with existing data
       */
      externalDuplicates?: number | null;
    };
  };
  /**
   * Geocoding results by location string (locationString → coordinates)
   */
  geocodingResults?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Processing results and statistics
   */
  results?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Processing errors by row
   */
  errors?:
    | {
        row: number;
        error: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Detailed error information and recovery attempts
   */
  errorLog?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Number of retry attempts made
   */
  retryAttempts?: number | null;
  /**
   * Timestamp of last retry attempt
   */
  lastRetryAt?: string | null;
  /**
   * Scheduled time for next retry attempt
   */
  nextRetryAt?: string | null;
  /**
   * Last stage completed successfully before failure
   */
  lastSuccessfulStage?:
    | (
        | 'analyze-duplicates'
        | 'detect-schema'
        | 'validate-schema'
        | 'await-approval'
        | 'geocode-batch'
        | 'create-events'
      )
    | null;
  displayTitle?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-files".
 */
export interface ImportFile {
  id: number;
  /**
   * Original user-friendly file name
   */
  originalName?: string | null;
  /**
   * The catalog this import belongs to (optional)
   */
  catalog?: (number | null) | Catalog;
  /**
   * Datasets detected in this import (optional)
   */
  datasets?: (number | Dataset)[] | null;
  /**
   * User who initiated the import
   */
  user: number | User;
  status?: ('pending' | 'parsing' | 'processing' | 'completed' | 'failed') | null;
  /**
   * Number of datasets detected in this catalog import
   */
  datasetsCount?: number | null;
  /**
   * Number of datasets successfully processed
   */
  datasetsProcessed?: number | null;
  /**
   * Information about detected sheets/datasets in the file
   */
  sheetMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Payload job ID for tracking the catalog parsing job
   */
  jobId?: string | null;
  importedAt?: string | null;
  completedAt?: string | null;
  /**
   * Detailed error information
   */
  errorLog?: string | null;
  /**
   * Rate limiting information for this import
   */
  rateLimitInfo?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Additional import context and metadata
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  quotaInfo?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Immutable audit trail of account deletions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deletion-audit-log".
 */
export interface DeletionAuditLog {
  id: number;
  /**
   * The ID of the deleted user
   */
  deletedUserId: number;
  /**
   * SHA256 hash of the deleted user's email (for privacy)
   */
  deletedUserEmailHash: string;
  /**
   * When the account was permanently deleted
   */
  deletedAt: string;
  /**
   * When the user requested deletion
   */
  deletionRequestedAt?: string | null;
  /**
   * User who initiated the deletion (null for self-deletion after grace period)
   */
  deletedBy?: (number | null) | User;
  /**
   * How the deletion was initiated
   */
  deletionType: 'self' | 'admin' | 'scheduled';
  /**
   * Optional reason for deletion (admin-initiated only)
   */
  reason?: string | null;
  /**
   * Summary of public data transferred to system user
   */
  dataTransferred?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Summary of private data permanently deleted
   */
  dataDeleted?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Hashed IP address of the requester (for security)
   */
  ipAddressHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage scheduled URL imports that run automatically
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scheduled-imports".
 */
export interface ScheduledImport {
  id: number;
  /**
   * Descriptive name for this scheduled import
   */
  name: string;
  /**
   * User who created this scheduled import
   */
  createdBy: number | User;
  /**
   * Optional description of what this import does
   */
  description?: string | null;
  /**
   * Enable/disable this scheduled import
   */
  enabled?: boolean | null;
  /**
   * URL to fetch data from
   */
  sourceUrl: string;
  /**
   * Authentication configuration for accessing the URL
   */
  authConfig?: {
    type?: ('none' | 'api-key' | 'bearer' | 'basic') | null;
    /**
     * API key to include in request header
     */
    apiKey?: string | null;
    /**
     * Header name for API key
     */
    apiKeyHeader?: string | null;
    /**
     * Bearer token for Authorization header
     */
    bearerToken?: string | null;
    /**
     * Username for basic authentication
     */
    username?: string | null;
    /**
     * Password for basic authentication
     */
    password?: string | null;
    /**
     * Additional custom headers as JSON object
     */
    customHeaders?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Catalog to import data into
   */
  catalog: number | Catalog;
  /**
   * Target dataset for single-sheet imports
   */
  dataset?: (number | null) | Dataset;
  /**
   * Configuration for Excel files with multiple sheets
   */
  multiSheetConfig?: {
    /**
     * Enable multi-sheet import configuration
     */
    enabled?: boolean | null;
    /**
     * Configure dataset mapping for each sheet
     */
    sheets?:
      | {
          /**
           * Sheet name or index (0-based)
           */
          sheetIdentifier: string;
          /**
           * Target dataset for this sheet
           */
          dataset: number | Dataset;
          /**
           * Skip this sheet if not found in the file
           */
          skipIfMissing?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Choose scheduling method
   */
  scheduleType: 'frequency' | 'cron';
  /**
   * How often to run the import
   */
  frequency?: ('hourly' | 'daily' | 'weekly' | 'monthly') | null;
  /**
   * Cron expression (e.g., '0 * /6 * * *' for every 6 hours)
   */
  cronExpression?: string | null;
  /**
   * Template for generated import names. Available variables: {{name}}, {{date}}, {{time}}, {{url}}
   */
  importNameTemplate?: string | null;
  /**
   * Enable webhook URL for triggering this import on-demand
   */
  webhookEnabled?: boolean | null;
  webhookToken?: string | null;
  /**
   * POST to this URL to trigger the import
   */
  webhookUrl?: string | null;
  /**
   * Retry behavior configuration
   */
  retryConfig?: {
    /**
     * Maximum number of retry attempts
     */
    maxRetries?: number | null;
    /**
     * Delay between retries in minutes
     */
    retryDelayMinutes?: number | null;
    /**
     * Use exponential backoff for retries
     */
    exponentialBackoff?: boolean | null;
  };
  /**
   * Advanced import options
   */
  advancedOptions?: {
    /**
     * Maximum time to wait for response in minutes
     */
    timeoutMinutes?: number | null;
    /**
     * Skip duplicate content checking
     */
    skipDuplicateChecking?: boolean | null;
    /**
     * Automatically approve schema changes
     */
    autoApproveSchema?: boolean | null;
    /**
     * Maximum file size in MB (leave empty for no limit)
     */
    maxFileSizeMB?: number | null;
    /**
     * Enable HTTP caching for URL responses
     */
    useHttpCache?: boolean | null;
    /**
     * Bypass cache when manually triggering the import
     */
    bypassCacheOnManual?: boolean | null;
    /**
     * Respect Cache-Control headers from the server
     */
    respectCacheControl?: boolean | null;
  };
  /**
   * Last execution time
   */
  lastRun?: string | null;
  /**
   * Next scheduled execution time
   */
  nextRun?: string | null;
  /**
   * Status of last execution
   */
  lastStatus?: ('success' | 'failed' | 'running') | null;
  /**
   * Error message from last failed execution
   */
  lastError?: string | null;
  /**
   * Current retry attempt count
   */
  currentRetries?: number | null;
  /**
   * Execution statistics
   */
  statistics?: {
    /**
     * Total number of executions
     */
    totalRuns?: number | null;
    /**
     * Number of successful executions
     */
    successfulRuns?: number | null;
    /**
     * Number of failed executions
     */
    failedRuns?: number | null;
    /**
     * Average execution duration in milliseconds
     */
    averageDuration?: number | null;
  };
  /**
   * History of recent executions
   */
  executionHistory?:
    | {
        executedAt: string;
        status: 'success' | 'failed';
        /**
         * Duration in milliseconds
         */
        duration?: number | null;
        recordsImported?: number | null;
        error?: string | null;
        /**
         * Background job ID
         */
        jobId?: string | null;
        /**
         * How this execution was triggered
         */
        triggeredBy?: ('schedule' | 'webhook' | 'manual' | 'system') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  dataset: number | Dataset;
  /**
   * Denormalized from dataset.isPublic for zero-query access control
   */
  datasetIsPublic?: boolean | null;
  /**
   * Denormalized from catalog.owner for zero-query owner access control
   */
  catalogOwnerId?: number | null;
  /**
   * The import job that created this event
   */
  importJob?: (number | null) | ImportJob;
  /**
   * Generic data in JSON format (JSONB indexed for fast queries)
   */
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Geographic coordinates (WGS84)
   */
  location?: {
    latitude?: number | null;
    longitude?: number | null;
  };
  /**
   * Source and validation of coordinate data
   */
  coordinateSource?: {
    type?: ('import' | 'geocoded' | 'manual' | 'none') | null;
    importColumns?: {
      /**
       * Column name containing latitude
       */
      latitudeColumn?: string | null;
      /**
       * Column name containing longitude
       */
      longitudeColumn?: string | null;
      /**
       * Column name if coordinates were combined
       */
      combinedColumn?: string | null;
      /**
       * Format of coordinates (decimal, DMS, etc.)
       */
      format?: string | null;
    };
    /**
     * Confidence in coordinate accuracy (0-1)
     */
    confidence?: number | null;
    /**
     * Normalized address returned by geocoder
     */
    normalizedAddress?: string | null;
    validationStatus?: ('valid' | 'out_of_range' | 'suspicious_zero' | 'swapped' | 'invalid') | null;
  };
  /**
   * When the actual event occurred
   */
  eventTimestamp?: string | null;
  /**
   * Location/venue name for display (e.g., 'Reichstag', 'Kottbusser Platz')
   */
  locationName?: string | null;
  /**
   * Validation errors if any
   */
  validationErrors?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Geocoding metadata and information
   */
  geocodingInfo?: {
    /**
     * Original address string from import
     */
    originalAddress?: string | null;
    /**
     * Geocoding processing status
     */
    geocodingStatus?: ('pending' | 'success' | 'failed') | null;
    /**
     * Geocoding provider used
     */
    provider?: ('google' | 'nominatim' | 'manual') | null;
    /**
     * Geocoding confidence score (0-1)
     */
    confidence?: number | null;
    /**
     * Normalized address returned by geocoder
     */
    normalizedAddress?: string | null;
  };
  /**
   * Unique identifier for deduplication (format: datasetId:strategy:value)
   */
  uniqueId: string;
  /**
   * Original ID from source system (when using external ID strategy)
   */
  sourceId?: string | null;
  /**
   * SHA256 hash of data content for duplicate detection
   */
  contentHash?: string | null;
  /**
   * Batch number within import for tracking
   */
  importBatch?: number | null;
  /**
   * Schema version number this event was validated against
   */
  schemaVersionNumber?: number | null;
  validationStatus?: ('pending' | 'valid' | 'invalid' | 'transformed') | null;
  /**
   * Record of any type transformations applied
   */
  transformations?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-usage".
 */
export interface UserUsage {
  id: number;
  /**
   * The user this usage record belongs to
   */
  user: number | User;
  /**
   * URL fetches performed today (resets at midnight UTC)
   */
  urlFetchesToday?: number | null;
  /**
   * Files uploaded today (resets at midnight UTC)
   */
  fileUploadsToday?: number | null;
  /**
   * Import jobs created today (resets at midnight UTC)
   */
  importJobsToday?: number | null;
  /**
   * Currently active scheduled imports
   */
  currentActiveSchedules?: number | null;
  /**
   * Total events created by this user (lifetime)
   */
  totalEventsCreated?: number | null;
  /**
   * Current number of catalogs owned by this user
   */
  currentCatalogs?: number | null;
  /**
   * Last time daily counters were reset
   */
  lastResetDate?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * User who uploaded this media
   */
  createdBy?: (number | null) | User;
  /**
   * Alternative text for accessibility
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "location-cache".
 */
export interface LocationCache {
  id: number;
  /**
   * Original address string
   */
  originalAddress: string;
  /**
   * Normalized address for better matching
   */
  normalizedAddress: string;
  /**
   * Latitude coordinate (WGS84)
   */
  latitude: number;
  /**
   * Longitude coordinate (WGS84)
   */
  longitude: number;
  /**
   * Name of the geocoding provider used
   */
  provider: string;
  /**
   * Confidence score (0-1)
   */
  confidence?: number | null;
  /**
   * Number of times this cached result was used
   */
  hitCount?: number | null;
  /**
   * Last time this cached result was accessed
   */
  lastUsed?: string | null;
  /**
   * Parsed address components
   */
  components?: {
    /**
     * Street number
     */
    streetNumber?: string | null;
    /**
     * Street name
     */
    streetName?: string | null;
    /**
     * City name
     */
    city?: string | null;
    /**
     * State/Region/Province
     */
    region?: string | null;
    /**
     * Postal/ZIP code
     */
    postalCode?: string | null;
    /**
     * Country name
     */
    country?: string | null;
  };
  /**
   * Additional provider-specific metadata
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage geocoding provider configurations
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "geocoding-providers".
 */
export interface GeocodingProvider {
  id: number;
  /**
   * Unique name for this provider instance (e.g., 'Google Primary', 'Nominatim EU')
   */
  name: string;
  /**
   * The geocoding service provider
   */
  type: 'google' | 'nominatim' | 'opencage';
  /**
   * Enable this provider instance
   */
  enabled?: boolean | null;
  /**
   * Provider priority (1 = highest priority, 1000 = lowest)
   */
  priority: number;
  /**
   * Maximum requests per second for this provider
   */
  rateLimit?: number | null;
  /**
   * Provider-specific settings
   */
  config?: {
    google?: {
      /**
       * Google Maps Geocoding API key
       */
      apiKey: string;
      /**
       * ISO 3166-1 alpha-2 country code for result bias (e.g., 'US', 'GB')
       */
      region?: string | null;
      /**
       * Language for returned results (e.g., 'en', 'de', 'fr')
       */
      language?: string | null;
    };
    nominatim?: {
      /**
       * Nominatim server URL
       */
      baseUrl: string;
      /**
       * User agent string for requests (required by Nominatim policy)
       */
      userAgent: string;
      /**
       * Contact email for high-volume usage (recommended)
       */
      email?: string | null;
      /**
       * Comma-separated ISO 3166-1 alpha-2 codes to limit results (e.g., 'us,ca,gb')
       */
      countrycodes?: string | null;
      /**
       * Include detailed address components in results
       */
      addressdetails?: boolean | null;
      /**
       * Include additional OSM tags in results
       */
      extratags?: boolean | null;
    };
    opencage?: {
      /**
       * OpenCage Geocoding API key
       */
      apiKey: string;
      /**
       * ISO 639-1 language code for results (e.g., 'en', 'de', 'fr')
       */
      language?: string | null;
      /**
       * ISO 3166-1 alpha-2 country code to restrict results (e.g., 'US', 'DE')
       */
      countrycode?: string | null;
      /**
       * Restrict results to a specific geographic area
       */
      bounds?: {
        enabled?: boolean | null;
        southwest?: {
          lat?: number | null;
          lng?: number | null;
        };
        northeast?: {
          lat?: number | null;
          lng?: number | null;
        };
      };
      /**
       * Include additional metadata like timezone, currency, etc.
       */
      annotations?: boolean | null;
      /**
       * Abbreviate street names and components
       */
      abbrv?: boolean | null;
    };
  };
  /**
   * Tags for organizing and filtering providers
   */
  tags?:
    | (
        | 'production'
        | 'development'
        | 'testing'
        | 'backup'
        | 'primary'
        | 'secondary'
        | 'region-us'
        | 'region-eu'
        | 'region-asia'
        | 'region-global'
        | 'high-volume'
        | 'low-volume'
        | 'free-tier'
        | 'paid-tier'
      )[]
    | null;
  /**
   * Provider usage statistics (automatically updated)
   */
  statistics?: {
    totalRequests?: number | null;
    successfulRequests?: number | null;
    failedRequests?: number | null;
    lastUsed?: string | null;
    averageResponseTime?: number | null;
  };
  /**
   * Internal notes about this provider instance
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL-friendly identifier (auto-generated from name if not provided)
   */
  slug?: string | null;
  pageBuilder: (
    | {
        title: string;
        subtitle?: string | null;
        description?: string | null;
        background?: ('gradient' | 'grid') | null;
        buttons?:
          | {
              text: string;
              link: string;
              variant?: ('default' | 'outline') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        sectionTitle?: string | null;
        sectionDescription?: string | null;
        columns?: ('1' | '2' | '3' | '4') | null;
        features: {
          icon:
            | 'email'
            | 'business'
            | 'support'
            | 'location'
            | 'map'
            | 'timeline'
            | 'insights'
            | 'github'
            | 'bluesky'
            | 'mastodon'
            | 'linkedin'
            | 'facebook'
            | 'instagram'
            | 'youtube'
            | 'x';
          title: string;
          description: string;
          accent?: ('none' | 'primary' | 'secondary' | 'accent' | 'muted') | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'features';
      }
    | {
        stats: {
          value: string;
          label: string;
          icon?:
            | (
                | 'email'
                | 'business'
                | 'support'
                | 'location'
                | 'map'
                | 'timeline'
                | 'insights'
                | 'github'
                | 'bluesky'
                | 'mastodon'
                | 'linkedin'
                | 'facebook'
                | 'instagram'
                | 'youtube'
                | 'x'
              )
            | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'stats';
      }
    | {
        sectionTitle?: string | null;
        variant?: ('grid-2' | 'grid-3' | 'grid-4' | 'compact') | null;
        items: {
          icon:
            | 'email'
            | 'business'
            | 'support'
            | 'location'
            | 'map'
            | 'timeline'
            | 'insights'
            | 'github'
            | 'bluesky'
            | 'mastodon'
            | 'linkedin'
            | 'facebook'
            | 'instagram'
            | 'youtube'
            | 'x';
          label: string;
          value: string;
          link?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'detailsGrid';
      }
    | {
        sectionTitle?: string | null;
        variant?: ('vertical' | 'compact') | null;
        items: {
          /**
           * Display date (e.g., '2024', 'March 2024', 'Q1 2024')
           */
          date: string;
          title: string;
          description: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'timeline';
      }
    | {
        sectionTitle?: string | null;
        variant?: ('grid' | 'single' | 'masonry') | null;
        items: {
          quote: string;
          author: string;
          /**
           * Optional role or title (e.g., 'Open Source Contributor')
           */
          role?: string | null;
          /**
           * Optional icon to display as avatar
           */
          avatar?:
            | (
                | 'email'
                | 'business'
                | 'support'
                | 'location'
                | 'map'
                | 'timeline'
                | 'insights'
                | 'github'
                | 'bluesky'
                | 'mastodon'
                | 'linkedin'
                | 'facebook'
                | 'instagram'
                | 'youtube'
                | 'x'
              )
            | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'testimonials';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        headline: string;
        description?: string | null;
        buttonText: string;
        buttonLink: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        /**
         * Optional headline text (default: 'Stay Mapped In')
         */
        headline?: string | null;
        /**
         * Email input placeholder text
         */
        placeholder?: string | null;
        /**
         * Submit button text
         */
        buttonText?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'newsletterForm';
      }
    | {
        /**
         * Main headline text
         */
        headline?: string | null;
        /**
         * Supporting description text
         */
        description?: string | null;
        /**
         * Email input placeholder text
         */
        placeholder?: string | null;
        /**
         * Submit button text
         */
        buttonText?: string | null;
        variant?: ('default' | 'elevated' | 'centered') | null;
        size?: ('default' | 'lg' | 'xl') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'newsletterCTA';
      }
  )[];
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          | 'inline'
          | 'dataset-detection'
          | 'detect-schema'
          | 'analyze-duplicates'
          | 'validate-schema'
          | 'create-schema-version'
          | 'geocode-batch'
          | 'create-events'
          | 'cleanup-approval-locks'
          | 'url-fetch'
          | 'schedule-manager'
          | 'cleanup-stuck-scheduled-imports'
          | 'process-pending-retries'
          | 'quota-reset'
          | 'cache-cleanup'
          | 'schema-maintenance'
          | 'data-export'
          | 'data-export-cleanup';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    | (
        | 'inline'
        | 'dataset-detection'
        | 'detect-schema'
        | 'analyze-duplicates'
        | 'validate-schema'
        | 'create-schema-version'
        | 'geocode-batch'
        | 'create-events'
        | 'cleanup-approval-locks'
        | 'url-fetch'
        | 'schedule-manager'
        | 'cleanup-stuck-scheduled-imports'
        | 'process-pending-retries'
        | 'quota-reset'
        | 'cache-cleanup'
        | 'schema-maintenance'
        | 'data-export'
        | 'data-export-cleanup'
      )
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'catalogs';
        value: number | Catalog;
      } | null)
    | ({
        relationTo: 'data-exports';
        value: number | DataExport;
      } | null)
    | ({
        relationTo: 'datasets';
        value: number | Dataset;
      } | null)
    | ({
        relationTo: 'dataset-schemas';
        value: number | DatasetSchema;
      } | null)
    | ({
        relationTo: 'deletion-audit-log';
        value: number | DeletionAuditLog;
      } | null)
    | ({
        relationTo: 'import-files';
        value: number | ImportFile;
      } | null)
    | ({
        relationTo: 'import-jobs';
        value: number | ImportJob;
      } | null)
    | ({
        relationTo: 'scheduled-imports';
        value: number | ScheduledImport;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'user-usage';
        value: number | UserUsage;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'location-cache';
        value: number | LocationCache;
      } | null)
    | ({
        relationTo: 'geocoding-providers';
        value: number | GeocodingProvider;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: number | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalogs_select".
 */
export interface CatalogsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  slug?: T;
  createdBy?: T;
  isPublic?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-exports_select".
 */
export interface DataExportsSelect<T extends boolean = true> {
  user?: T;
  status?: T;
  requestedAt?: T;
  completedAt?: T;
  expiresAt?: T;
  filePath?: T;
  fileSize?: T;
  downloadCount?: T;
  summary?: T;
  errorLog?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datasets_select".
 */
export interface DatasetsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  slug?: T;
  catalog?: T;
  catalogCreatorId?: T;
  catalogIsPublic?: T;
  language?: T;
  isPublic?: T;
  createdBy?: T;
  metadata?: T;
  idStrategy?:
    | T
    | {
        type?: T;
        externalIdPath?: T;
        computedIdFields?:
          | T
          | {
              fieldPath?: T;
              id?: T;
            };
        duplicateStrategy?: T;
      };
  schemaConfig?:
    | T
    | {
        enabled?: T;
        locked?: T;
        autoGrow?: T;
        autoApproveNonBreaking?: T;
        strictValidation?: T;
        allowTransformations?: T;
        maxSchemaDepth?: T;
        enumThreshold?: T;
        enumMode?: T;
      };
  deduplicationConfig?:
    | T
    | {
        enabled?: T;
        strategy?: T;
      };
  fieldMetadata?: T;
  typeTransformations?:
    | T
    | {
        fieldPath?: T;
        fromType?: T;
        toType?: T;
        transformStrategy?: T;
        customTransform?: T;
        enabled?: T;
        id?: T;
      };
  importTransforms?:
    | T
    | {
        id?: T;
        type?: T;
        from?: T;
        to?: T;
        active?: T;
        addedAt?: T;
        addedBy?: T;
        confidence?: T;
        autoDetected?: T;
      };
  enumDetection?:
    | T
    | {
        mode?: T;
        threshold?: T;
      };
  geoFieldDetection?:
    | T
    | {
        autoDetect?: T;
        latitudePath?: T;
        longitudePath?: T;
      };
  fieldMappingOverrides?:
    | T
    | {
        titlePath?: T;
        descriptionPath?: T;
        locationNamePath?: T;
        timestampPath?: T;
        latitudePath?: T;
        longitudePath?: T;
        locationPath?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dataset-schemas_select".
 */
export interface DatasetSchemasSelect<T extends boolean = true> {
  dataset?: T;
  versionNumber?: T;
  displayName?: T;
  schema?: T;
  fieldMetadata?: T;
  eventCountAtCreation?: T;
  schemaSummary?:
    | T
    | {
        totalFields?: T;
        newFields?:
          | T
          | {
              path?: T;
              id?: T;
            };
        removedFields?:
          | T
          | {
              path?: T;
              id?: T;
            };
        typeChanges?:
          | T
          | {
              path?: T;
              oldType?: T;
              newType?: T;
              id?: T;
            };
        enumChanges?:
          | T
          | {
              path?: T;
              addedValues?: T;
              removedValues?: T;
              id?: T;
            };
      };
  importSources?:
    | T
    | {
        import?: T;
        recordCount?: T;
        batchCount?: T;
        id?: T;
      };
  approvalRequired?: T;
  approvedBy?: T;
  approvalNotes?: T;
  autoApproved?: T;
  conflicts?: T;
  fieldMappings?:
    | T
    | {
        titlePath?: T;
        descriptionPath?: T;
        locationNamePath?: T;
        timestampPath?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deletion-audit-log_select".
 */
export interface DeletionAuditLogSelect<T extends boolean = true> {
  deletedUserId?: T;
  deletedUserEmailHash?: T;
  deletedAt?: T;
  deletionRequestedAt?: T;
  deletedBy?: T;
  deletionType?: T;
  reason?: T;
  dataTransferred?: T;
  dataDeleted?: T;
  ipAddressHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-files_select".
 */
export interface ImportFilesSelect<T extends boolean = true> {
  originalName?: T;
  catalog?: T;
  datasets?: T;
  user?: T;
  status?: T;
  datasetsCount?: T;
  datasetsProcessed?: T;
  sheetMetadata?: T;
  jobId?: T;
  importedAt?: T;
  completedAt?: T;
  errorLog?: T;
  rateLimitInfo?: T;
  metadata?: T;
  quotaInfo?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-jobs_select".
 */
export interface ImportJobsSelect<T extends boolean = true> {
  importFile?: T;
  dataset?: T;
  sheetIndex?: T;
  stage?: T;
  progress?:
    | T
    | {
        stages?: T;
        overallPercentage?: T;
        estimatedCompletionTime?: T;
      };
  schema?: T;
  schemaBuilderState?: T;
  detectedFieldMappings?:
    | T
    | {
        titlePath?: T;
        descriptionPath?: T;
        locationNamePath?: T;
        timestampPath?: T;
        latitudePath?: T;
        longitudePath?: T;
        locationPath?: T;
      };
  schemaValidation?:
    | T
    | {
        isCompatible?: T;
        breakingChanges?: T;
        newFields?: T;
        transformSuggestions?: T;
        requiresApproval?: T;
        approvalReason?: T;
        approved?: T;
        approvedBy?: T;
        approvedAt?: T;
      };
  datasetSchemaVersion?: T;
  duplicates?:
    | T
    | {
        strategy?: T;
        internal?: T;
        external?: T;
        summary?:
          | T
          | {
              totalRows?: T;
              uniqueRows?: T;
              internalDuplicates?: T;
              externalDuplicates?: T;
            };
      };
  geocodingResults?: T;
  results?: T;
  errors?:
    | T
    | {
        row?: T;
        error?: T;
        id?: T;
      };
  errorLog?: T;
  retryAttempts?: T;
  lastRetryAt?: T;
  nextRetryAt?: T;
  lastSuccessfulStage?: T;
  displayTitle?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scheduled-imports_select".
 */
export interface ScheduledImportsSelect<T extends boolean = true> {
  name?: T;
  createdBy?: T;
  description?: T;
  enabled?: T;
  sourceUrl?: T;
  authConfig?:
    | T
    | {
        type?: T;
        apiKey?: T;
        apiKeyHeader?: T;
        bearerToken?: T;
        username?: T;
        password?: T;
        customHeaders?: T;
      };
  catalog?: T;
  dataset?: T;
  multiSheetConfig?:
    | T
    | {
        enabled?: T;
        sheets?:
          | T
          | {
              sheetIdentifier?: T;
              dataset?: T;
              skipIfMissing?: T;
              id?: T;
            };
      };
  scheduleType?: T;
  frequency?: T;
  cronExpression?: T;
  importNameTemplate?: T;
  webhookEnabled?: T;
  webhookToken?: T;
  webhookUrl?: T;
  retryConfig?:
    | T
    | {
        maxRetries?: T;
        retryDelayMinutes?: T;
        exponentialBackoff?: T;
      };
  advancedOptions?:
    | T
    | {
        timeoutMinutes?: T;
        skipDuplicateChecking?: T;
        autoApproveSchema?: T;
        maxFileSizeMB?: T;
        useHttpCache?: T;
        bypassCacheOnManual?: T;
        respectCacheControl?: T;
      };
  lastRun?: T;
  nextRun?: T;
  lastStatus?: T;
  lastError?: T;
  currentRetries?: T;
  statistics?:
    | T
    | {
        totalRuns?: T;
        successfulRuns?: T;
        failedRuns?: T;
        averageDuration?: T;
      };
  executionHistory?:
    | T
    | {
        executedAt?: T;
        status?: T;
        duration?: T;
        recordsImported?: T;
        error?: T;
        jobId?: T;
        triggeredBy?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  dataset?: T;
  datasetIsPublic?: T;
  catalogOwnerId?: T;
  importJob?: T;
  data?: T;
  location?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  coordinateSource?:
    | T
    | {
        type?: T;
        importColumns?:
          | T
          | {
              latitudeColumn?: T;
              longitudeColumn?: T;
              combinedColumn?: T;
              format?: T;
            };
        confidence?: T;
        normalizedAddress?: T;
        validationStatus?: T;
      };
  eventTimestamp?: T;
  locationName?: T;
  validationErrors?: T;
  geocodingInfo?:
    | T
    | {
        originalAddress?: T;
        geocodingStatus?: T;
        provider?: T;
        confidence?: T;
        normalizedAddress?: T;
      };
  uniqueId?: T;
  sourceId?: T;
  contentHash?: T;
  importBatch?: T;
  schemaVersionNumber?: T;
  validationStatus?: T;
  transformations?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  isActive?: T;
  lastLoginAt?: T;
  registrationSource?: T;
  trustLevel?: T;
  quotas?:
    | T
    | {
        maxActiveSchedules?: T;
        maxUrlFetchesPerDay?: T;
        maxFileUploadsPerDay?: T;
        maxEventsPerImport?: T;
        maxTotalEvents?: T;
        maxImportJobsPerDay?: T;
        maxFileSizeMB?: T;
        maxCatalogsPerUser?: T;
      };
  customQuotas?: T;
  deletionStatus?: T;
  deletionRequestedAt?: T;
  deletionScheduledAt?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-usage_select".
 */
export interface UserUsageSelect<T extends boolean = true> {
  user?: T;
  urlFetchesToday?: T;
  fileUploadsToday?: T;
  importJobsToday?: T;
  currentActiveSchedules?: T;
  totalEventsCreated?: T;
  currentCatalogs?: T;
  lastResetDate?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  createdBy?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "location-cache_select".
 */
export interface LocationCacheSelect<T extends boolean = true> {
  originalAddress?: T;
  normalizedAddress?: T;
  latitude?: T;
  longitude?: T;
  provider?: T;
  confidence?: T;
  hitCount?: T;
  lastUsed?: T;
  components?:
    | T
    | {
        streetNumber?: T;
        streetName?: T;
        city?: T;
        region?: T;
        postalCode?: T;
        country?: T;
      };
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "geocoding-providers_select".
 */
export interface GeocodingProvidersSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  enabled?: T;
  priority?: T;
  rateLimit?: T;
  config?:
    | T
    | {
        google?:
          | T
          | {
              apiKey?: T;
              region?: T;
              language?: T;
            };
        nominatim?:
          | T
          | {
              baseUrl?: T;
              userAgent?: T;
              email?: T;
              countrycodes?: T;
              addressdetails?: T;
              extratags?: T;
            };
        opencage?:
          | T
          | {
              apiKey?: T;
              language?: T;
              countrycode?: T;
              bounds?:
                | T
                | {
                    enabled?: T;
                    southwest?:
                      | T
                      | {
                          lat?: T;
                          lng?: T;
                        };
                    northeast?:
                      | T
                      | {
                          lat?: T;
                          lng?: T;
                        };
                  };
              annotations?: T;
              abbrv?: T;
            };
      };
  tags?: T;
  statistics?:
    | T
    | {
        totalRequests?: T;
        successfulRequests?: T;
        failedRequests?: T;
        lastUsed?: T;
        averageResponseTime?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pageBuilder?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              subtitle?: T;
              description?: T;
              background?: T;
              buttons?:
                | T
                | {
                    text?: T;
                    link?: T;
                    variant?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              sectionTitle?: T;
              sectionDescription?: T;
              columns?: T;
              features?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    accent?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        detailsGrid?:
          | T
          | {
              sectionTitle?: T;
              variant?: T;
              items?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    value?: T;
                    link?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              sectionTitle?: T;
              variant?: T;
              items?:
                | T
                | {
                    date?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              sectionTitle?: T;
              variant?: T;
              items?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    role?: T;
                    avatar?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              headline?: T;
              description?: T;
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        newsletterForm?:
          | T
          | {
              headline?: T;
              placeholder?: T;
              buttonText?: T;
              id?: T;
              blockName?: T;
            };
        newsletterCTA?:
          | T
          | {
              headline?: T;
              description?: T;
              placeholder?: T;
              buttonText?: T;
              variant?: T;
              size?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-menu".
 */
export interface MainMenu {
  id: number;
  navItems?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Brief tagline or description for your brand
   */
  tagline: string;
  /**
   * Social media links (e.g., Twitter, GitHub, LinkedIn)
   */
  socialLinks?:
    | {
        platform: 'x' | 'bluesky' | 'mastodon' | 'github' | 'linkedin' | 'facebook' | 'instagram' | 'youtube';
        url: string;
        id?: string | null;
      }[]
    | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Newsletter subscription form settings
   */
  newsletter?: {
    /**
     * Show newsletter signup in footer
     */
    enabled?: boolean | null;
    /**
     * Newsletter section headline
     */
    headline?: string | null;
    /**
     * Email input placeholder text
     */
    placeholder?: string | null;
    /**
     * Submit button text
     */
    buttonText?: string | null;
  };
  /**
   * Copyright text (e.g., © 2024 TimeTiles. All rights reserved.)
   */
  copyright: string;
  /**
   * Optional credits or attribution text
   */
  credits?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding".
 */
export interface Branding {
  id: number;
  /**
   * The name displayed in the header and browser tab title
   */
  siteName?: string | null;
  /**
   * Meta description for SEO and social sharing (og:description)
   */
  siteDescription?: string | null;
  /**
   * Logo for light backgrounds. Recommended: 128x128px PNG with transparency.
   */
  logoLight?: (number | null) | Media;
  /**
   * Logo for dark backgrounds. Recommended: 128x128px PNG with transparency.
   */
  logoDark?: (number | null) | Media;
  /**
   * Source image for light theme favicons. Recommended: 512x512px square PNG.
   */
  faviconSourceLight?: (number | null) | Media;
  /**
   * Source image for dark theme favicons. Recommended: 512x512px square PNG.
   */
  faviconSourceDark?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  newsletter?: {
    /**
     * External newsletter service endpoint to POST email subscriptions (e.g., Listmonk: http://localhost:9000/api/subscribers, Mailchimp API, etc.)
     */
    serviceUrl?: string | null;
    /**
     * Optional: Authorization header for the newsletter service (e.g., 'Bearer YOUR_TOKEN' or 'Basic BASE64_CREDENTIALS'). Leave empty if not required.
     */
    authHeader?: string | null;
  };
  geocoding?: {
    /**
     * Enable or disable geocoding globally for event imports
     */
    enabled?: boolean | null;
    /**
     * When enabled, will try alternative providers if the primary provider fails
     */
    fallbackEnabled?: boolean | null;
    providerSelection?: {
      /**
       * How to select which geocoding provider to use
       */
      strategy?: ('priority' | 'tag-based') | null;
      /**
       * Only use providers with these tags (for tag-based strategy)
       */
      requiredTags?: ('production' | 'development' | 'testing' | 'primary' | 'secondary' | 'backup')[] | null;
    };
    caching?: {
      /**
       * Cache geocoding results to reduce API calls and improve performance
       */
      enabled?: boolean | null;
      /**
       * How long to keep cached geocoding results (in days)
       */
      ttlDays?: number | null;
    };
  };
  /**
   * Enable or disable major application features
   */
  featureFlags?: {
    /**
     * When enabled, users can create private imports visible only to themselves
     */
    allowPrivateImports?: boolean | null;
    /**
     * When enabled, users can create automated URL-based import schedules
     */
    enableScheduledImports?: boolean | null;
    /**
     * When enabled, new users can self-register accounts
     */
    enableRegistration?: boolean | null;
    /**
     * When enabled, new events can be created (via imports or API)
     */
    enableEventCreation?: boolean | null;
    /**
     * When enabled, users can create new datasets
     */
    enableDatasetCreation?: boolean | null;
    /**
     * When enabled, users can create new import jobs
     */
    enableImportCreation?: boolean | null;
    /**
     * When enabled, scheduled import jobs will execute automatically
     */
    enableScheduledJobExecution?: boolean | null;
    /**
     * When enabled, URL fetches for scheduled imports are cached to reduce requests
     */
    enableUrlFetchCaching?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-menu_select".
 */
export interface MainMenuSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  newsletter?:
    | T
    | {
        enabled?: T;
        headline?: T;
        placeholder?: T;
        buttonText?: T;
      };
  copyright?: T;
  credits?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding_select".
 */
export interface BrandingSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  logoLight?: T;
  logoDark?: T;
  faviconSourceLight?: T;
  faviconSourceDark?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  newsletter?:
    | T
    | {
        serviceUrl?: T;
        authHeader?: T;
      };
  geocoding?:
    | T
    | {
        enabled?: T;
        fallbackEnabled?: T;
        providerSelection?:
          | T
          | {
              strategy?: T;
              requiredTags?: T;
            };
        caching?:
          | T
          | {
              enabled?: T;
              ttlDays?: T;
            };
      };
  featureFlags?:
    | T
    | {
        allowPrivateImports?: T;
        enableScheduledImports?: T;
        enableRegistration?: T;
        enableEventCreation?: T;
        enableDatasetCreation?: T;
        enableImportCreation?: T;
        enableScheduledJobExecution?: T;
        enableUrlFetchCaching?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskDataset-detection".
 */
export interface TaskDatasetDetection {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskDetect-schema".
 */
export interface TaskDetectSchema {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskAnalyze-duplicates".
 */
export interface TaskAnalyzeDuplicates {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskValidate-schema".
 */
export interface TaskValidateSchema {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreate-schema-version".
 */
export interface TaskCreateSchemaVersion {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGeocode-batch".
 */
export interface TaskGeocodeBatch {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreate-events".
 */
export interface TaskCreateEvents {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCleanup-approval-locks".
 */
export interface TaskCleanupApprovalLocks {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskUrl-fetch".
 */
export interface TaskUrlFetch {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedule-manager".
 */
export interface TaskScheduleManager {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCleanup-stuck-scheduled-imports".
 */
export interface TaskCleanupStuckScheduledImports {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskProcess-pending-retries".
 */
export interface TaskProcessPendingRetries {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskQuota-reset".
 */
export interface TaskQuotaReset {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCache-cleanup".
 */
export interface TaskCacheCleanup {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchema-maintenance".
 */
export interface TaskSchemaMaintenance {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskData-export".
 */
export interface TaskDataExport {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskData-export-cleanup".
 */
export interface TaskDataExportCleanup {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}