self-hosted-runner:
  # Labels of self-hosted runner in array of strings.
  labels: []

# Configuration variables in array of strings defined in your repository or
# organization. `null` means disabling configuration variables check.
# Empty array means no configuration variable is allowed.
config-variables: null

# Minimal ignores for actionlint  
paths:
  .github/workflows/**/*.yml:
    ignore:
      # SC2086: Only ignore for GITHUB_STEP_SUMMARY which is a file path
      # provided by GitHub Actions and guaranteed to not have spaces
      - 'SC2086:.*GITHUB_STEP_SUMMARY'
      
      # SC2016: Expressions don't expand in single quotes
      # These are intentional - we want the literal ${VARIABLE} string
      # not the expanded value (e.g., in sed commands)
      - 'SC2016:'
