module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    // Custom rules based on the TimeTiles commit guidelines
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'web',
        'docs',
        'ui',
        'geocoding',
        'import',
        'auth',
        'db',
        'deps',
      ],
    ],
    'scope-empty': [0, 'never'],
    'subject-case': [2, 'always', ['lower-case', 'sentence-case']],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'type-case': [2, 'always', 'lower-case'],
    'type-empty': [2, 'never'],
    'scope-case': [2, 'always', 'lower-case'],
    'header-max-length': [2, 'always', 72],
    'body-leading-blank': [2, 'always'],
    'footer-leading-blank': [2, 'always'],
    'body-max-line-length': [2, 'always', 100],
  },
};