packages:
  - "apps/*"
  - "packages/*"

catalog:
  # Core framework
  react: ^19.2.4
  react-dom: ^19.2.4
  next: ^16.1.6
  next-themes: ^0.4.6
  zod: ^4.3.6
  # Type definitions
  "@types/react": ^19.2.10
  "@types/react-dom": ^19.2.3
  "@types/node": ^25.1.0
  # Build tooling
  typescript: ^5.9.3
  eslint: ^9.39.2
  prettier: ^3.8.1
  tsx: ^4.21.0
  "@svgr/webpack": ^8.1.0
  # Testing
  vitest: ^4.0.18
  "@vitest/coverage-v8": ^4.0.18
  # Charting
  echarts: ^6.0.0
  echarts-for-react: ^3.0.6
  # Shared libraries
  lucide-react: ^0.563.0
  franc: ^6.2.0
