import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "language" varchar;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "country_codes" varchar;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "location_bias_enabled" boolean DEFAULT false;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "location_bias_lat" numeric;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "location_bias_lon" numeric;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "location_bias_zoom" numeric DEFAULT 10;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "bounding_box_enabled" boolean DEFAULT false;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "bounding_box_min_lon" numeric;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "bounding_box_min_lat" numeric;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "bounding_box_max_lon" numeric;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "bounding_box_max_lat" numeric;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "api_key" varchar;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "base_url" varchar;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "user_agent" varchar DEFAULT 'TimeTiles-App/1.0';
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "result_limit" numeric DEFAULT 5;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_language" varchar;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_country_codes" varchar;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_location_bias_enabled" boolean DEFAULT false;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_location_bias_lat" numeric;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_location_bias_lon" numeric;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_location_bias_zoom" numeric DEFAULT 10;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_bounding_box_enabled" boolean DEFAULT false;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_bounding_box_min_lon" numeric;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_bounding_box_min_lat" numeric;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_bounding_box_max_lon" numeric;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_bounding_box_max_lat" numeric;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_api_key" varchar;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_base_url" varchar;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_user_agent" varchar DEFAULT 'TimeTiles-App/1.0';
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_result_limit" numeric DEFAULT 5;
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_google_api_key";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_google_region";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_google_language";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_nominatim_base_url";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_nominatim_user_agent";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_nominatim_countrycodes";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_nominatim_addressdetails";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_nominatim_extratags";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_opencage_api_key";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_opencage_language";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_opencage_countrycode";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_opencage_bounds_enabled";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_opencage_bounds_southwest_lat";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_opencage_bounds_southwest_lng";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_opencage_bounds_northeast_lat";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_opencage_bounds_northeast_lng";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_opencage_annotations";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_opencage_abbrv";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_locationiq_api_key";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_locationiq_countrycodes";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_photon_base_url";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_photon_language";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_photon_limit";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_photon_location_bias_enabled";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_photon_location_bias_lat";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_photon_location_bias_lon";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_photon_location_bias_zoom";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_photon_bbox_enabled";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_photon_bbox_min_lon";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_photon_bbox_min_lat";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_photon_bbox_max_lon";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "config_photon_bbox_max_lat";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_google_api_key";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_google_region";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_google_language";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_nominatim_base_url";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_nominatim_user_agent";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_nominatim_countrycodes";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_nominatim_addressdetails";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_nominatim_extratags";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_opencage_api_key";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_opencage_language";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_opencage_countrycode";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_opencage_bounds_enabled";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_opencage_bounds_southwest_lat";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_opencage_bounds_southwest_lng";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_opencage_bounds_northeast_lat";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_opencage_bounds_northeast_lng";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_opencage_annotations";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_opencage_abbrv";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_locationiq_api_key";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_locationiq_countrycodes";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_photon_base_url";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_photon_language";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_photon_limit";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_photon_location_bias_enabled";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_photon_location_bias_lat";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_photon_location_bias_lon";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_photon_location_bias_zoom";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_photon_bbox_enabled";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_photon_bbox_min_lon";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_photon_bbox_min_lat";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_photon_bbox_max_lon";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_config_photon_bbox_max_lat";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_google_api_key" varchar;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_google_region" varchar;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_google_language" varchar DEFAULT 'en';
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_nominatim_base_url" varchar DEFAULT 'https://nominatim.openstreetmap.org';
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_nominatim_user_agent" varchar DEFAULT 'TimeTiles-App/1.0';
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_nominatim_countrycodes" varchar;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_nominatim_addressdetails" boolean DEFAULT true;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_nominatim_extratags" boolean DEFAULT false;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_opencage_api_key" varchar;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_opencage_language" varchar DEFAULT 'en';
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_opencage_countrycode" varchar;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_opencage_bounds_enabled" boolean DEFAULT false;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_opencage_bounds_southwest_lat" numeric;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_opencage_bounds_southwest_lng" numeric;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_opencage_bounds_northeast_lat" numeric;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_opencage_bounds_northeast_lng" numeric;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_opencage_annotations" boolean DEFAULT true;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_opencage_abbrv" boolean DEFAULT false;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_locationiq_api_key" varchar;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_locationiq_countrycodes" varchar;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_photon_base_url" varchar DEFAULT 'https://photon.komoot.io';
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_photon_language" varchar;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_photon_limit" numeric DEFAULT 5;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_photon_location_bias_enabled" boolean DEFAULT false;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_photon_location_bias_lat" numeric;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_photon_location_bias_lon" numeric;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_photon_location_bias_zoom" numeric DEFAULT 10;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_photon_bbox_enabled" boolean DEFAULT false;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_photon_bbox_min_lon" numeric;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_photon_bbox_min_lat" numeric;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_photon_bbox_max_lon" numeric;
  ALTER TABLE "payload"."geocoding_providers" ADD COLUMN "config_photon_bbox_max_lat" numeric;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_google_api_key" varchar;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_google_region" varchar;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_google_language" varchar DEFAULT 'en';
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_nominatim_base_url" varchar DEFAULT 'https://nominatim.openstreetmap.org';
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_nominatim_user_agent" varchar DEFAULT 'TimeTiles-App/1.0';
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_nominatim_countrycodes" varchar;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_nominatim_addressdetails" boolean DEFAULT true;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_nominatim_extratags" boolean DEFAULT false;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_opencage_api_key" varchar;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_opencage_language" varchar DEFAULT 'en';
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_opencage_countrycode" varchar;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_opencage_bounds_enabled" boolean DEFAULT false;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_opencage_bounds_southwest_lat" numeric;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_opencage_bounds_southwest_lng" numeric;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_opencage_bounds_northeast_lat" numeric;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_opencage_bounds_northeast_lng" numeric;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_opencage_annotations" boolean DEFAULT true;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_opencage_abbrv" boolean DEFAULT false;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_locationiq_api_key" varchar;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_locationiq_countrycodes" varchar;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_photon_base_url" varchar DEFAULT 'https://photon.komoot.io';
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_photon_language" varchar;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_photon_limit" numeric DEFAULT 5;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_photon_location_bias_enabled" boolean DEFAULT false;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_photon_location_bias_lat" numeric;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_photon_location_bias_lon" numeric;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_photon_location_bias_zoom" numeric DEFAULT 10;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_photon_bbox_enabled" boolean DEFAULT false;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_photon_bbox_min_lon" numeric;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_photon_bbox_min_lat" numeric;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_photon_bbox_max_lon" numeric;
  ALTER TABLE "payload"."_geocoding_providers_v" ADD COLUMN "version_config_photon_bbox_max_lat" numeric;
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "language";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "country_codes";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "location_bias_enabled";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "location_bias_lat";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "location_bias_lon";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "location_bias_zoom";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "bounding_box_enabled";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "bounding_box_min_lon";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "bounding_box_min_lat";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "bounding_box_max_lon";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "bounding_box_max_lat";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "api_key";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "base_url";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "user_agent";
  ALTER TABLE "payload"."geocoding_providers" DROP COLUMN "result_limit";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_language";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_country_codes";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_location_bias_enabled";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_location_bias_lat";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_location_bias_lon";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_location_bias_zoom";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_bounding_box_enabled";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_bounding_box_min_lon";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_bounding_box_min_lat";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_bounding_box_max_lon";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_bounding_box_max_lat";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_api_key";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_base_url";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_user_agent";
  ALTER TABLE "payload"."_geocoding_providers_v" DROP COLUMN "version_result_limit";`)
}
