#!/usr/bin/env tsx

/**
 * Verify the Pagefind search index in the static export.
 *
 * Nextra's search UI fetches `/_pagefind/pagefind.js` at runtime; the index is
 * generated by running `pagefind` over `out/` after `next build`. If that step
 * is skipped or produces an empty index, search silently breaks in production
 * (the site otherwise deploys fine). This script fails the build instead.
 *
 * @module
 */

import fs from "fs";
import path, { dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const pagefindDir = path.join(__dirname, "../out/_pagefind");

// The docs site has far more pages than this; the threshold only guards
// against a structurally valid but near-empty index.
const MIN_INDEXED_PAGES = 10;

interface PagefindEntry {
  version?: string;
  languages?: Record<string, { page_count?: number }>;
}

const fail = (message: string): never => {
  console.error(`✗ ${message}`);
  console.error("  Search on the deployed docs site would be broken.");
  process.exit(1);
};

const main = (): void => {
  console.log("Verifying Pagefind search index...\n");

  // Files Nextra's search client loads at runtime
  for (const file of ["pagefind.js", "pagefind-entry.json"]) {
    if (!fs.existsSync(path.join(pagefindDir, file))) {
      fail(`Missing out/_pagefind/${file} — was pagefind run after next build?`);
    }
  }

  const entry: PagefindEntry = JSON.parse(fs.readFileSync(path.join(pagefindDir, "pagefind-entry.json"), "utf-8"));
  const languages = Object.entries(entry.languages ?? {});
  if (languages.length === 0) {
    fail("pagefind-entry.json contains no language indexes");
  }

  const totalPages = languages.reduce((sum, [, lang]) => sum + (lang.page_count ?? 0), 0);
  if (totalPages < MIN_INDEXED_PAGES) {
    fail(`Index only covers ${totalPages} pages (expected at least ${MIN_INDEXED_PAGES})`);
  }

  console.log(`✓ Search index OK (pagefind ${entry.version ?? "unknown"})`);
  for (const [language, lang] of languages) {
    console.log(`  ${language}: ${lang.page_count ?? 0} pages`);
  }
};

try {
  main();
} catch (error) {
  console.error("Error:", error);
  process.exit(1);
}
