services:
  nginx:
    volumes:
      - /Users/user/code/jf/timetiles/deployment/nginx-test/nginx.conf:/etc/nginx/nginx.conf:ro
      - /Users/user/code/jf/timetiles/deployment/nginx-test/sites-enabled:/etc/nginx/sites-enabled:ro
      - /Users/user/code/jf/timetiles/deployment/nginx-test/proxy-headers.conf:/etc/nginx/proxy-headers.conf:ro
      - /Users/user/code/jf/timetiles/deployment/ssl:/etc/letsencrypt:ro
      - certbot-webroot:/var/www/certbot:ro

volumes:
  certbot-webroot:
