/**
 * ID strategy and deduplication card for the field mapping step.
 *
 * @module
 * @category Components
 */
"use client";

import { Card, CardContent, Label } from "@timetiles/ui";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@timetiles/ui/components/select";
import { HashIcon } from "lucide-react";
import { useTranslations } from "next-intl";

import type { FieldMapping } from "@/lib/types/ingest-wizard";

export interface IdStrategyCardProps {
  idStrategy: FieldMapping["idStrategy"];
  idField: string | null;
  headers: string[];
  deduplicationStrategy: string;
  onFieldChange: (field: keyof FieldMapping, value: string | null) => void;
  onDeduplicationChange: (value: string) => void;
  /** Render without Card/CardHeader wrapper (for embedding inside another container) */
  bare?: boolean;
  /** Disable all controls when importing into an existing dataset */
  locked?: boolean;
}

export const IdStrategyCard = ({
  idStrategy,
  idField,
  headers,
  deduplicationStrategy,
  onFieldChange,
  onDeduplicationChange,
  bare = false,
  locked = false,
}: Readonly<IdStrategyCardProps>) => {
  const t = useTranslations("Ingest");

  const ID_STRATEGIES = [
    { value: "content-hash", label: t("idContentHash"), description: t("idContentHashDescription") },
    { value: "external", label: t("idUseSourceId"), description: t("idUseSourceIdDescription") },
    { value: "auto-generate", label: t("idAutoGenerate"), description: t("idAutoGenerateDescription") },
  ] as const;

  const DEDUP_STRATEGIES = [
    { value: "skip", label: t("dedupSkipDuplicates"), description: t("dedupSkipDuplicatesDescription") },
    { value: "update", label: t("dedupUpdateExisting"), description: t("dedupUpdateExistingDescription") },
    { value: "version", label: t("dedupCreateVersions"), description: t("dedupCreateVersionsDescription") },
  ] as const;

  const showIdField = idStrategy === "external";

  const handleStrategyChange = (val: string) => onFieldChange("idStrategy", val);

  const handleIdFieldChange = (val: string) => onFieldChange("idField", val === "__none__" ? null : val);

  const content = (
    <div className="space-y-4">
      <div className="grid gap-4 sm:grid-cols-2">
        <div className="space-y-2">
          <Label htmlFor="id-strategy" className="text-foreground">
            {t("idGeneration")}
          </Label>
          <Select value={idStrategy} onValueChange={handleStrategyChange} disabled={locked}>
            <SelectTrigger id="id-strategy" className="h-11">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {ID_STRATEGIES.map((strategy) => (
                <SelectItem key={strategy.value} value={strategy.value}>
                  {strategy.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <div className="space-y-2">
          <Label htmlFor="dedup-strategy" className="text-foreground">
            {t("duplicateHandling")}
          </Label>
          <Select value={deduplicationStrategy} onValueChange={onDeduplicationChange} disabled={locked}>
            <SelectTrigger id="dedup-strategy" className="h-11">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {DEDUP_STRATEGIES.map((strategy) => (
                <SelectItem key={strategy.value} value={strategy.value}>
                  {strategy.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      </div>

      {showIdField && (
        <div className="space-y-2">
          <Label htmlFor="id-field" className="text-foreground">
            {t("idField")}
          </Label>
          <Select value={idField ?? "__none__"} onValueChange={handleIdFieldChange} disabled={locked}>
            <SelectTrigger id="id-field" className="h-11">
              <SelectValue placeholder={t("selectColumn")} />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="__none__">{t("selectColumn")}</SelectItem>
              {headers.map((header) => (
                <SelectItem key={header} value={header}>
                  {header}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      )}

      {locked && <p className="text-muted-foreground text-sm italic">{t("idStrategyLocked")}</p>}
    </div>
  );

  if (bare) return content;

  return (
    <Card className="overflow-hidden">
      <div className="border-primary/10 bg-card/30 border-b px-6 py-4">
        <div className="flex items-center gap-3">
          <div className="bg-primary/10 flex h-10 w-10 items-center justify-center rounded-sm">
            <HashIcon className="text-primary h-5 w-5" />
          </div>
          <div>
            <h3 className="text-foreground font-serif text-lg font-semibold">{t("identityAndDuplicates")}</h3>
            <p className="text-muted-foreground text-sm">{t("identityAndDuplicatesDescription")}</p>
          </div>
        </div>
      </div>
      <CardContent className="p-6">{content}</CardContent>
    </Card>
  );
};
