/**
 * ID strategy and deduplication card for the field mapping step.
 *
 * @module
 * @category Components
 */
"use client";

import { Card, CardContent, Label } from "@timetiles/ui";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@timetiles/ui/components/select";
import { HashIcon } from "lucide-react";
import { useTranslations } from "next-intl";

import type { FieldMapping } from "@/lib/ingest/types/wizard";

export const ID_STRATEGY_CONFIG = [
  {
    value: "content-hash",
    optionLabelKey: "idContentHash",
    summaryLabelKey: "idStrategyContentHash",
    descriptionKey: "idContentHashDescription",
  },
  {
    value: "external",
    optionLabelKey: "idUseSourceId",
    summaryLabelKey: "idStrategyExternal",
    descriptionKey: "idUseSourceIdDescription",
  },
  {
    value: "auto-generate",
    optionLabelKey: "idAutoGenerate",
    summaryLabelKey: "idStrategyAutoGenerate",
    descriptionKey: "idAutoGenerateDescription",
  },
] as const;

export const DEDUP_STRATEGY_CONFIG = [
  {
    value: "skip",
    optionLabelKey: "dedupSkipDuplicates",
    summaryLabelKey: "dedupSkip",
    descriptionKey: "dedupSkipDuplicatesDescription",
  },
  {
    value: "update",
    optionLabelKey: "dedupUpdateExisting",
    summaryLabelKey: "dedupUpdate",
    descriptionKey: "dedupUpdateExistingDescription",
  },
  {
    value: "version",
    optionLabelKey: "dedupCreateVersions",
    summaryLabelKey: "dedupVersion",
    descriptionKey: "dedupCreateVersionsDescription",
  },
] as const;

export interface IdStrategyCardProps {
  idStrategy: FieldMapping["idStrategy"];
  idField: string | null;
  headers: string[];
  deduplicationStrategy: string;
  onFieldChange: (field: keyof FieldMapping, value: string | null) => void;
  onDeduplicationChange: (value: string) => void;
  /** Render without Card/CardHeader wrapper (for embedding inside another container) */
  bare?: boolean;
  /** Disable all controls when importing into an existing dataset */
  locked?: boolean;
}

export const IdStrategyCard = ({
  idStrategy,
  idField,
  headers,
  deduplicationStrategy,
  onFieldChange,
  onDeduplicationChange,
  bare = false,
  locked = false,
}: Readonly<IdStrategyCardProps>) => {
  const t = useTranslations("Ingest");

  const idStrategies = ID_STRATEGY_CONFIG.map((strategy) => ({
    value: strategy.value,
    label: t(strategy.optionLabelKey),
    description: t(strategy.descriptionKey),
  }));
  const deduplicationStrategies = DEDUP_STRATEGY_CONFIG.map((strategy) => ({
    value: strategy.value,
    label: t(strategy.optionLabelKey),
    description: t(strategy.descriptionKey),
  }));

  const showIdField = idStrategy === "external";

  const handleStrategyChange = (val: string) => onFieldChange("idStrategy", val);

  const handleIdFieldChange = (val: string) => onFieldChange("idField", val === "__none__" ? null : val);

  const content = (
    <div className="space-y-4">
      <div className="grid gap-4 sm:grid-cols-2">
        <div className="space-y-2">
          <Label htmlFor="id-strategy" className="text-foreground">
            {t("idGeneration")}
          </Label>
          <Select value={idStrategy} onValueChange={handleStrategyChange} disabled={locked}>
            <SelectTrigger id="id-strategy" className="h-11">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {idStrategies.map((strategy) => (
                <SelectItem key={strategy.value} value={strategy.value}>
                  {strategy.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <div className="space-y-2">
          <Label htmlFor="dedup-strategy" className="text-foreground">
            {t("duplicateHandling")}
          </Label>
          <Select value={deduplicationStrategy} onValueChange={onDeduplicationChange} disabled={locked}>
            <SelectTrigger id="dedup-strategy" className="h-11">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {deduplicationStrategies.map((strategy) => (
                <SelectItem key={strategy.value} value={strategy.value}>
                  {strategy.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      </div>

      {showIdField && (
        <div className="space-y-2">
          <Label htmlFor="id-field" className="text-foreground">
            {t("idField")}
          </Label>
          <Select value={idField ?? "__none__"} onValueChange={handleIdFieldChange} disabled={locked}>
            <SelectTrigger id="id-field" className="h-11">
              <SelectValue placeholder={t("selectColumn")} />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="__none__">{t("selectColumn")}</SelectItem>
              {headers.map((header) => (
                <SelectItem key={header} value={header}>
                  {header}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      )}

      {locked && <p className="text-muted-foreground text-sm italic">{t("idStrategyLocked")}</p>}
    </div>
  );

  if (bare) return content;

  return (
    <Card className="overflow-hidden">
      <div className="border-primary/10 bg-card/30 border-b px-6 py-4">
        <div className="flex items-center gap-3">
          <div className="bg-primary/10 flex h-10 w-10 items-center justify-center rounded-sm">
            <HashIcon className="text-primary h-5 w-5" />
          </div>
          <div>
            <h3 className="text-foreground font-serif text-lg font-semibold">{t("identityAndDuplicates")}</h3>
            <p className="text-muted-foreground text-sm">{t("identityAndDuplicatesDescription")}</p>
          </div>
        </div>
      </div>
      <CardContent className="p-6">{content}</CardContent>
    </Card>
  );
};
