/**
 * ID strategy and deduplication card for the field mapping step.
 *
 * @module
 * @category Components
 */
"use client";

import { Card, CardContent, Label } from "@timetiles/ui";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@timetiles/ui/components/select";
import { HashIcon } from "lucide-react";
import { useTranslations } from "next-intl";

import type { FieldMapping } from "@/lib/types/import-wizard";

export interface IdStrategyCardProps {
  idStrategy: FieldMapping["idStrategy"];
  idField: string | null;
  headers: string[];
  deduplicationStrategy: string;
  onFieldChange: (field: keyof FieldMapping, value: string | null) => void;
  onDeduplicationChange: (value: string) => void;
}

export const IdStrategyCard = ({
  idStrategy,
  idField,
  headers,
  deduplicationStrategy,
  onFieldChange,
  onDeduplicationChange,
}: Readonly<IdStrategyCardProps>) => {
  const t = useTranslations("Import");

  const ID_STRATEGIES = [
    { value: "auto", label: t("idAutoGenerate"), description: t("idAutoGenerateDescription") },
    { value: "external", label: t("idUseSourceId"), description: t("idUseSourceIdDescription") },
    { value: "computed", label: t("idComputeFromFields"), description: t("idComputeFromFieldsDescription") },
    { value: "hybrid", label: t("idHybrid"), description: t("idHybridDescription") },
  ] as const;

  const DEDUP_STRATEGIES = [
    { value: "skip", label: t("dedupSkipDuplicates"), description: t("dedupSkipDuplicatesDescription") },
    { value: "update", label: t("dedupUpdateExisting"), description: t("dedupUpdateExistingDescription") },
    { value: "version", label: t("dedupCreateVersions"), description: t("dedupCreateVersionsDescription") },
  ] as const;

  const showIdField = idStrategy === "external" || idStrategy === "hybrid";

  const handleStrategyChange = (val: string) => onFieldChange("idStrategy", val);

  const handleIdFieldChange = (val: string) => onFieldChange("idField", val === "__none__" ? null : val);

  return (
    <Card className="overflow-hidden">
      <div className="border-cartographic-navy/10 bg-cartographic-cream/30 border-b px-6 py-4">
        <div className="flex items-center gap-3">
          <div className="bg-cartographic-navy/10 flex h-10 w-10 items-center justify-center rounded-sm">
            <HashIcon className="text-cartographic-navy h-5 w-5" />
          </div>
          <div>
            <h3 className="text-cartographic-charcoal font-serif text-lg font-semibold">
              {t("identityAndDuplicates")}
            </h3>
            <p className="text-cartographic-navy/70 text-sm">{t("identityAndDuplicatesDescription")}</p>
          </div>
        </div>
      </div>
      <CardContent className="space-y-4 p-6">
        <div className="grid gap-4 sm:grid-cols-2">
          <div className="space-y-2">
            <Label htmlFor="id-strategy" className="text-cartographic-charcoal">
              {t("idGeneration")}
            </Label>
            <Select value={idStrategy} onValueChange={handleStrategyChange}>
              <SelectTrigger id="id-strategy" className="h-11">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {ID_STRATEGIES.map((strategy) => (
                  <SelectItem key={strategy.value} value={strategy.value}>
                    {strategy.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <Label htmlFor="dedup-strategy" className="text-cartographic-charcoal">
              {t("duplicateHandling")}
            </Label>
            <Select value={deduplicationStrategy} onValueChange={onDeduplicationChange}>
              <SelectTrigger id="dedup-strategy" className="h-11">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {DEDUP_STRATEGIES.map((strategy) => (
                  <SelectItem key={strategy.value} value={strategy.value}>
                    {strategy.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>

        {showIdField && (
          <div className="space-y-2">
            <Label htmlFor="id-field" className="text-cartographic-charcoal">
              {t("idField")}
            </Label>
            <Select value={idField ?? "__none__"} onValueChange={handleIdFieldChange}>
              <SelectTrigger id="id-field" className="h-11">
                <SelectValue placeholder={t("selectColumn")} />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="__none__">{t("selectColumn")}</SelectItem>
                {headers.map((header) => (
                  <SelectItem key={header} value={header}>
                    {header}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        )}
      </CardContent>
    </Card>
  );
};
