#!/bin/bash
# TimeTiles Bootstrap - Step 11: fail2ban Configuration
# Installs and configures fail2ban for brute force protection

run_step() {
    # Check if fail2ban should be skipped
    if [[ "${SKIP_FAIL2BAN:-false}" == "true" ]]; then
        print_skip "fail2ban setup skipped (SKIP_FAIL2BAN=true)"
        return 0
    fi

    local ssh_port="${SSH_PORT:-22}"

    print_step "Installing fail2ban..."
    apt-get install -y -qq fail2ban

    print_step "Configuring fail2ban jails..."

    # Create local jail configuration (overrides defaults)
    cat > /etc/fail2ban/jail.local << EOF
# TimeTiles fail2ban configuration
# Generated by bootstrap script

[DEFAULT]
# Use UFW for banning
banaction = ufw
banaction_allports = ufw

# Default ban settings
bantime = 3600
findtime = 600
maxretry = 5

# Ignore local networks (adjust as needed)
ignoreip = 127.0.0.1/8 ::1

[sshd]
enabled = true
port = ${ssh_port}
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 3600
findtime = 600

# nginx rate limit violations (if using limit_req with logging)
[nginx-limit-req]
enabled = true
port = http,https
filter = nginx-limit-req
logpath = /var/log/nginx/error.log
maxretry = 5
bantime = 600
findtime = 120
EOF

    print_info "Created /etc/fail2ban/jail.local"

    # Ensure fail2ban can work with ufw
    print_step "Configuring fail2ban to use UFW..."

    # Create ufw action if it doesn't exist or is outdated
    cat > /etc/fail2ban/action.d/ufw.conf << 'EOF'
# fail2ban action for UFW
[Definition]
actionstart =
actionstop =
actioncheck =
actionban = ufw insert 1 deny from <ip> to any
actionunban = ufw delete deny from <ip> to any
EOF

    print_info "Created UFW action for fail2ban"

    # Restart fail2ban to apply changes
    print_step "Starting fail2ban service..."
    systemctl enable fail2ban
    systemctl restart fail2ban

    # Wait a moment for fail2ban to start
    sleep 2

    # Show status
    print_step "fail2ban status:"
    fail2ban-client status || true
    fail2ban-client status sshd || true

    print_success "fail2ban configured and running"
}
