#!/bin/bash
# TimeTiles Bootstrap - Step 11: fail2ban Configuration
# Installs and configures fail2ban for brute force protection

run_step() {
    # Check if fail2ban should be skipped
    if [[ "${SKIP_FAIL2BAN:-false}" == "true" ]]; then
        print_skip "fail2ban setup skipped (SKIP_FAIL2BAN=true)"
        return 0
    fi

    local ssh_port="${SSH_PORT:-22}"

    print_step "Installing fail2ban..."
    apt-get install -y -qq fail2ban

    print_step "Configuring fail2ban jails..."

    # Create local jail configuration (overrides defaults)
    cat > /etc/fail2ban/jail.local << EOF
# TimeTiles fail2ban configuration
# Generated by bootstrap script

[DEFAULT]
# Use UFW for banning
banaction = ufw
banaction_allports = ufw

# Default ban settings
bantime = 3600
findtime = 600
maxretry = 5

# Ignore local networks (adjust as needed)
ignoreip = 127.0.0.1/8 ::1

[sshd]
enabled = true
port = ${ssh_port}
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 3600
findtime = 600
EOF

    # The nginx jail is only added when the log it watches actually exists.
    #
    # nginx runs as a CONTAINER here and logs through Docker's json-file
    # driver, so on a stock deployment nothing ever creates
    # /var/log/nginx/error.log on the host. fail2ban >= 0.10 refuses to start
    # the whole server when a jail's logpath is missing — so unconditionally
    # writing this jail took down the sshd jail with it, and the swallowed
    # restart failure below meant the step still reported "configured and
    # running" while no brute-force protection existed at all.
    if [[ -f /var/log/nginx/error.log ]]; then
        cat >> /etc/fail2ban/jail.local << 'EOF'

# nginx rate limit violations (host-side nginx log is present)
[nginx-limit-req]
enabled = true
port = http,https
filter = nginx-limit-req
logpath = /var/log/nginx/error.log
maxretry = 5
bantime = 600
findtime = 120
EOF
        print_info "Enabled nginx-limit-req jail"
    else
        print_info "No host nginx log - nginx-limit-req jail not enabled (nginx runs in a container)"
    fi

    print_info "Created /etc/fail2ban/jail.local"

    # Ensure fail2ban can work with ufw
    print_step "Configuring fail2ban to use UFW..."

    # Create ufw action if it doesn't exist or is outdated
    cat > /etc/fail2ban/action.d/ufw.conf << 'EOF'
# fail2ban action for UFW
[Definition]
actionstart =
actionstop =
actioncheck =
actionban = ufw insert 1 deny from <ip> to any
actionunban = ufw delete deny from <ip> to any
EOF

    print_info "Created UFW action for fail2ban"

    # Restart fail2ban to apply changes
    print_step "Starting fail2ban service..."
    systemctl enable fail2ban
    if ! systemctl restart fail2ban; then
        print_error "fail2ban failed to start"
        journalctl -u fail2ban --no-pager -n 20 || true
        die "fail2ban startup failed"
    fi

    # Wait a moment for fail2ban to start
    sleep 2

    # Confirm it is still up: fail2ban can exit shortly after a "successful"
    # restart when a jail turns out to be unusable, and this step used to
    # report success regardless.
    if ! systemctl is-active --quiet fail2ban; then
        print_error "fail2ban is not running after restart"
        journalctl -u fail2ban --no-pager -n 20 || true
        die "fail2ban did not stay running"
    fi

    # Show status
    print_step "fail2ban status:"
    fail2ban-client status || true
    fail2ban-client status sshd || true

    print_success "fail2ban configured and running"
}
